### ISSUE TITLE
Downloads are not possible ...

### ISSUE THREAD

**Issue by grezniczek** [dymosoftware/Beta-Version#1]
... as apparently you are over your quota.

Maybe you need to host large installers somewhere else, or buy more bandwidth here on GitHub.

**Comment by dymosoftware** [comment]
Yes, sorry for this inconvenience. Our purchases area is working on buy more bandwidth. In the meantime, you can download the zip file of whole repo and just execute DCD Windows 150-beta version installer.

![image](https://user-images.githubusercontent.com/57638744/152185141-74845b4c-f8b2-4679-a7e4-997f455060f6.png)

**Comment by grezniczek** [comment]
This will only include the metadata for the large files.

Attempts to clone the repo with the GitHub desktop client will result in the above quota error. This applies to forks, too.

**Comment by marvinvdongen** [comment]
Confirmed. Cloning repo does **not** work, same bandwidth issue.

**Comment by marvinvdongen** [comment]
Can't you upload the Windows files temporarily on wetransfer.com or your own site so we can at least continue?

**Comment by dymosoftware** [comment]
Sorry guys, we have WeTransfer link [here](https://we.tl/t-N28h4PEEgI). Please try to download it from there.

**Comment by dymosoftware** [comment]
Downloads are available.
